//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeHomeAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDC_Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PDC_Room()
        {
            this.PDC_Room1 = new HashSet<PDC_Room>();
            this.PDC_Room11 = new HashSet<PDC_Room>();
            this.PDC_Room12 = new HashSet<PDC_Room>();
            this.PDC_Room13 = new HashSet<PDC_Room>();
            this.PDC_Sensor = new HashSet<PDC_Sensor>();
        }
    
        public int RoomID { get; set; }
        public string RoomName { get; set; }
        public int CustomerID { get; set; }
        public int FloorID { get; set; }
        public Nullable<int> RoomIDNorth { get; set; }
        public Nullable<bool> DoorNorth { get; set; }
        public Nullable<int> RoomIDEast { get; set; }
        public Nullable<bool> DoorEast { get; set; }
        public Nullable<int> RoomIDSouth { get; set; }
        public Nullable<bool> DoorSouth { get; set; }
        public Nullable<int> RoomIDWest { get; set; }
        public Nullable<bool> DoorWest { get; set; }
    
        public virtual PDC_Customer PDC_Customer { get; set; }
        public virtual PDC_Floor PDC_Floor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDC_Room> PDC_Room1 { get; set; }
        public virtual PDC_Room PDC_Room2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDC_Room> PDC_Room11 { get; set; }
        public virtual PDC_Room PDC_Room3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDC_Room> PDC_Room12 { get; set; }
        public virtual PDC_Room PDC_Room4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDC_Room> PDC_Room13 { get; set; }
        public virtual PDC_Room PDC_Room5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDC_Sensor> PDC_Sensor { get; set; }
    }
}
