//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeHomeAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDC_SensorEvent
    {
        public int EventID { get; set; }
        public int SensorID { get; set; }
        public System.DateTime EventTime { get; set; }
        public string Detail { get; set; }
    
        public virtual PDC_Sensor PDC_Sensor { get; set; }
    }
}
