//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeHomeAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDC_Floor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PDC_Floor()
        {
            this.PDC_Room = new HashSet<PDC_Room>();
        }
    
        public int FloorID { get; set; }
        public int FloorNum { get; set; }
        public int NoOfRooms { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual PDC_Customer PDC_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDC_Room> PDC_Room { get; set; }
    }
}
