//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeHomeAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDC_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PDC_Customer()
        {
            this.PDC_Floor = new HashSet<PDC_Floor>();
            this.PDC_Room = new HashSet<PDC_Room>();
        }
    
        public int CustomerID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string SystemState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDC_Floor> PDC_Floor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDC_Room> PDC_Room { get; set; }
    }
}
