//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeHomeAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SafeHomeEntities : DbContext
    {
        public SafeHomeEntities()
            : base("name=SafeHomeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PDC_Customer> PDC_Customer { get; set; }
        public virtual DbSet<PDC_Floor> PDC_Floor { get; set; }
        public virtual DbSet<PDC_Room> PDC_Room { get; set; }
        public virtual DbSet<PDC_Sensor> PDC_Sensor { get; set; }
        public virtual DbSet<PDC_SensorEvent> PDC_SensorEvent { get; set; }
        public virtual DbSet<PDC_SensorType> PDC_SensorType { get; set; }
    }
}
