//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SafeHomeWebsite.SafeHomeAPIService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SafeHomeAPISoap", Namespace="http://www.safehome-gre.com/")]
    public partial class SafeHomeAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSystemStateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSensorEventsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeactivateSystemOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActivateSystemOperationCompleted;
        
        private System.Threading.SendOrPostCallback RestartSystemOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitReadingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SafeHomeAPI() {
            this.Url = global::SafeHomeWebsite.Properties.Settings.Default.SafeHomeWebsite_SafeHomeAPIService_SafeHomeAPI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSystemStateCompletedEventHandler GetSystemStateCompleted;
        
        /// <remarks/>
        public event GetSensorEventsCompletedEventHandler GetSensorEventsCompleted;
        
        /// <remarks/>
        public event DeactivateSystemCompletedEventHandler DeactivateSystemCompleted;
        
        /// <remarks/>
        public event ActivateSystemCompletedEventHandler ActivateSystemCompleted;
        
        /// <remarks/>
        public event RestartSystemCompletedEventHandler RestartSystemCompleted;
        
        /// <remarks/>
        public event SubmitReadingCompletedEventHandler SubmitReadingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.safehome-gre.com/GetSystemState", RequestNamespace="http://www.safehome-gre.com/", ResponseNamespace="http://www.safehome-gre.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSystemState(int customerID) {
            object[] results = this.Invoke("GetSystemState", new object[] {
                        customerID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSystemStateAsync(int customerID) {
            this.GetSystemStateAsync(customerID, null);
        }
        
        /// <remarks/>
        public void GetSystemStateAsync(int customerID, object userState) {
            if ((this.GetSystemStateOperationCompleted == null)) {
                this.GetSystemStateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSystemStateOperationCompleted);
            }
            this.InvokeAsync("GetSystemState", new object[] {
                        customerID}, this.GetSystemStateOperationCompleted, userState);
        }
        
        private void OnGetSystemStateOperationCompleted(object arg) {
            if ((this.GetSystemStateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSystemStateCompleted(this, new GetSystemStateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.safehome-gre.com/GetSensorEvents", RequestNamespace="http://www.safehome-gre.com/", ResponseNamespace="http://www.safehome-gre.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SensorEvent[] GetSensorEvents(int customerID) {
            object[] results = this.Invoke("GetSensorEvents", new object[] {
                        customerID});
            return ((SensorEvent[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSensorEventsAsync(int customerID) {
            this.GetSensorEventsAsync(customerID, null);
        }
        
        /// <remarks/>
        public void GetSensorEventsAsync(int customerID, object userState) {
            if ((this.GetSensorEventsOperationCompleted == null)) {
                this.GetSensorEventsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSensorEventsOperationCompleted);
            }
            this.InvokeAsync("GetSensorEvents", new object[] {
                        customerID}, this.GetSensorEventsOperationCompleted, userState);
        }
        
        private void OnGetSensorEventsOperationCompleted(object arg) {
            if ((this.GetSensorEventsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSensorEventsCompleted(this, new GetSensorEventsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.safehome-gre.com/DeactivateSystem", RequestNamespace="http://www.safehome-gre.com/", ResponseNamespace="http://www.safehome-gre.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeactivateSystem(int customerID) {
            object[] results = this.Invoke("DeactivateSystem", new object[] {
                        customerID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeactivateSystemAsync(int customerID) {
            this.DeactivateSystemAsync(customerID, null);
        }
        
        /// <remarks/>
        public void DeactivateSystemAsync(int customerID, object userState) {
            if ((this.DeactivateSystemOperationCompleted == null)) {
                this.DeactivateSystemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeactivateSystemOperationCompleted);
            }
            this.InvokeAsync("DeactivateSystem", new object[] {
                        customerID}, this.DeactivateSystemOperationCompleted, userState);
        }
        
        private void OnDeactivateSystemOperationCompleted(object arg) {
            if ((this.DeactivateSystemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeactivateSystemCompleted(this, new DeactivateSystemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.safehome-gre.com/ActivateSystem", RequestNamespace="http://www.safehome-gre.com/", ResponseNamespace="http://www.safehome-gre.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ActivateSystem(int customerID) {
            object[] results = this.Invoke("ActivateSystem", new object[] {
                        customerID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActivateSystemAsync(int customerID) {
            this.ActivateSystemAsync(customerID, null);
        }
        
        /// <remarks/>
        public void ActivateSystemAsync(int customerID, object userState) {
            if ((this.ActivateSystemOperationCompleted == null)) {
                this.ActivateSystemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivateSystemOperationCompleted);
            }
            this.InvokeAsync("ActivateSystem", new object[] {
                        customerID}, this.ActivateSystemOperationCompleted, userState);
        }
        
        private void OnActivateSystemOperationCompleted(object arg) {
            if ((this.ActivateSystemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivateSystemCompleted(this, new ActivateSystemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.safehome-gre.com/RestartSystem", RequestNamespace="http://www.safehome-gre.com/", ResponseNamespace="http://www.safehome-gre.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RestartSystem(int customerID) {
            object[] results = this.Invoke("RestartSystem", new object[] {
                        customerID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RestartSystemAsync(int customerID) {
            this.RestartSystemAsync(customerID, null);
        }
        
        /// <remarks/>
        public void RestartSystemAsync(int customerID, object userState) {
            if ((this.RestartSystemOperationCompleted == null)) {
                this.RestartSystemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRestartSystemOperationCompleted);
            }
            this.InvokeAsync("RestartSystem", new object[] {
                        customerID}, this.RestartSystemOperationCompleted, userState);
        }
        
        private void OnRestartSystemOperationCompleted(object arg) {
            if ((this.RestartSystemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RestartSystemCompleted(this, new RestartSystemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.safehome-gre.com/SubmitReading", RequestNamespace="http://www.safehome-gre.com/", ResponseNamespace="http://www.safehome-gre.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SubmitReading(int customerID, int sensorID, string detail) {
            object[] results = this.Invoke("SubmitReading", new object[] {
                        customerID,
                        sensorID,
                        detail});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitReadingAsync(int customerID, int sensorID, string detail) {
            this.SubmitReadingAsync(customerID, sensorID, detail, null);
        }
        
        /// <remarks/>
        public void SubmitReadingAsync(int customerID, int sensorID, string detail, object userState) {
            if ((this.SubmitReadingOperationCompleted == null)) {
                this.SubmitReadingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitReadingOperationCompleted);
            }
            this.InvokeAsync("SubmitReading", new object[] {
                        customerID,
                        sensorID,
                        detail}, this.SubmitReadingOperationCompleted, userState);
        }
        
        private void OnSubmitReadingOperationCompleted(object arg) {
            if ((this.SubmitReadingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitReadingCompleted(this, new SubmitReadingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.safehome-gre.com/")]
    public partial class SensorEvent {
        
        private int eventID1Field;
        
        private string roomName1Field;
        
        private string sensorType1Field;
        
        private string detail1Field;
        
        private System.DateTime eventTime1Field;
        
        /// <remarks/>
        public int EventID1 {
            get {
                return this.eventID1Field;
            }
            set {
                this.eventID1Field = value;
            }
        }
        
        /// <remarks/>
        public string RoomName1 {
            get {
                return this.roomName1Field;
            }
            set {
                this.roomName1Field = value;
            }
        }
        
        /// <remarks/>
        public string SensorType1 {
            get {
                return this.sensorType1Field;
            }
            set {
                this.sensorType1Field = value;
            }
        }
        
        /// <remarks/>
        public string Detail1 {
            get {
                return this.detail1Field;
            }
            set {
                this.detail1Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EventTime1 {
            get {
                return this.eventTime1Field;
            }
            set {
                this.eventTime1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetSystemStateCompletedEventHandler(object sender, GetSystemStateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSystemStateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSystemStateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetSensorEventsCompletedEventHandler(object sender, GetSensorEventsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSensorEventsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSensorEventsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SensorEvent[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SensorEvent[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeactivateSystemCompletedEventHandler(object sender, DeactivateSystemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeactivateSystemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeactivateSystemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ActivateSystemCompletedEventHandler(object sender, ActivateSystemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActivateSystemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActivateSystemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RestartSystemCompletedEventHandler(object sender, RestartSystemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RestartSystemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RestartSystemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SubmitReadingCompletedEventHandler(object sender, SubmitReadingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitReadingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitReadingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591