//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeHome.SafeHomeAPIServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SensorEvent", Namespace="http://www.safehome-gre.com/")]
    [System.SerializableAttribute()]
    public partial class SensorEvent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EventID1Field;
        
        private int SensorID1Field;
        
        private System.DateTime EventTime1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Detail1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EventID1 {
            get {
                return this.EventID1Field;
            }
            set {
                if ((this.EventID1Field.Equals(value) != true)) {
                    this.EventID1Field = value;
                    this.RaisePropertyChanged("EventID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SensorID1 {
            get {
                return this.SensorID1Field;
            }
            set {
                if ((this.SensorID1Field.Equals(value) != true)) {
                    this.SensorID1Field = value;
                    this.RaisePropertyChanged("SensorID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime EventTime1 {
            get {
                return this.EventTime1Field;
            }
            set {
                if ((this.EventTime1Field.Equals(value) != true)) {
                    this.EventTime1Field = value;
                    this.RaisePropertyChanged("EventTime1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Detail1 {
            get {
                return this.Detail1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Detail1Field, value) != true)) {
                    this.Detail1Field = value;
                    this.RaisePropertyChanged("Detail1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.safehome-gre.com/", ConfigurationName="SafeHomeAPIServices.SafeHomeAPISoap")]
    public interface SafeHomeAPISoap {
        
        // CODEGEN: Generating message contract since element name GetSystemStateResult from namespace http://www.safehome-gre.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.safehome-gre.com/GetSystemState", ReplyAction="*")]
        SafeHome.SafeHomeAPIServices.GetSystemStateResponse GetSystemState(SafeHome.SafeHomeAPIServices.GetSystemStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.safehome-gre.com/GetSystemState", ReplyAction="*")]
        System.Threading.Tasks.Task<SafeHome.SafeHomeAPIServices.GetSystemStateResponse> GetSystemStateAsync(SafeHome.SafeHomeAPIServices.GetSystemStateRequest request);
        
        // CODEGEN: Generating message contract since element name GetSensorEventsResult from namespace http://www.safehome-gre.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.safehome-gre.com/GetSensorEvents", ReplyAction="*")]
        SafeHome.SafeHomeAPIServices.GetSensorEventsResponse GetSensorEvents(SafeHome.SafeHomeAPIServices.GetSensorEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.safehome-gre.com/GetSensorEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<SafeHome.SafeHomeAPIServices.GetSensorEventsResponse> GetSensorEventsAsync(SafeHome.SafeHomeAPIServices.GetSensorEventsRequest request);
        
        // CODEGEN: Generating message contract since element name DeactivateSystemResult from namespace http://www.safehome-gre.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.safehome-gre.com/DeactivateSystem", ReplyAction="*")]
        SafeHome.SafeHomeAPIServices.DeactivateSystemResponse DeactivateSystem(SafeHome.SafeHomeAPIServices.DeactivateSystemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.safehome-gre.com/DeactivateSystem", ReplyAction="*")]
        System.Threading.Tasks.Task<SafeHome.SafeHomeAPIServices.DeactivateSystemResponse> DeactivateSystemAsync(SafeHome.SafeHomeAPIServices.DeactivateSystemRequest request);
        
        // CODEGEN: Generating message contract since element name ActivateSystemResult from namespace http://www.safehome-gre.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.safehome-gre.com/ActivateSystem", ReplyAction="*")]
        SafeHome.SafeHomeAPIServices.ActivateSystemResponse ActivateSystem(SafeHome.SafeHomeAPIServices.ActivateSystemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.safehome-gre.com/ActivateSystem", ReplyAction="*")]
        System.Threading.Tasks.Task<SafeHome.SafeHomeAPIServices.ActivateSystemResponse> ActivateSystemAsync(SafeHome.SafeHomeAPIServices.ActivateSystemRequest request);
        
        // CODEGEN: Generating message contract since element name RestartSystemResult from namespace http://www.safehome-gre.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.safehome-gre.com/RestartSystem", ReplyAction="*")]
        SafeHome.SafeHomeAPIServices.RestartSystemResponse RestartSystem(SafeHome.SafeHomeAPIServices.RestartSystemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.safehome-gre.com/RestartSystem", ReplyAction="*")]
        System.Threading.Tasks.Task<SafeHome.SafeHomeAPIServices.RestartSystemResponse> RestartSystemAsync(SafeHome.SafeHomeAPIServices.RestartSystemRequest request);
        
        // CODEGEN: Generating message contract since element name detail from namespace http://www.safehome-gre.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.safehome-gre.com/SubmitReading", ReplyAction="*")]
        SafeHome.SafeHomeAPIServices.SubmitReadingResponse SubmitReading(SafeHome.SafeHomeAPIServices.SubmitReadingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.safehome-gre.com/SubmitReading", ReplyAction="*")]
        System.Threading.Tasks.Task<SafeHome.SafeHomeAPIServices.SubmitReadingResponse> SubmitReadingAsync(SafeHome.SafeHomeAPIServices.SubmitReadingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemState", Namespace="http://www.safehome-gre.com/", Order=0)]
        public SafeHome.SafeHomeAPIServices.GetSystemStateRequestBody Body;
        
        public GetSystemStateRequest() {
        }
        
        public GetSystemStateRequest(SafeHome.SafeHomeAPIServices.GetSystemStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.safehome-gre.com/")]
    public partial class GetSystemStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int customerID;
        
        public GetSystemStateRequestBody() {
        }
        
        public GetSystemStateRequestBody(int customerID) {
            this.customerID = customerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemStateResponse", Namespace="http://www.safehome-gre.com/", Order=0)]
        public SafeHome.SafeHomeAPIServices.GetSystemStateResponseBody Body;
        
        public GetSystemStateResponse() {
        }
        
        public GetSystemStateResponse(SafeHome.SafeHomeAPIServices.GetSystemStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.safehome-gre.com/")]
    public partial class GetSystemStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSystemStateResult;
        
        public GetSystemStateResponseBody() {
        }
        
        public GetSystemStateResponseBody(string GetSystemStateResult) {
            this.GetSystemStateResult = GetSystemStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSensorEventsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSensorEvents", Namespace="http://www.safehome-gre.com/", Order=0)]
        public SafeHome.SafeHomeAPIServices.GetSensorEventsRequestBody Body;
        
        public GetSensorEventsRequest() {
        }
        
        public GetSensorEventsRequest(SafeHome.SafeHomeAPIServices.GetSensorEventsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.safehome-gre.com/")]
    public partial class GetSensorEventsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int customerID;
        
        public GetSensorEventsRequestBody() {
        }
        
        public GetSensorEventsRequestBody(int customerID) {
            this.customerID = customerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSensorEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSensorEventsResponse", Namespace="http://www.safehome-gre.com/", Order=0)]
        public SafeHome.SafeHomeAPIServices.GetSensorEventsResponseBody Body;
        
        public GetSensorEventsResponse() {
        }
        
        public GetSensorEventsResponse(SafeHome.SafeHomeAPIServices.GetSensorEventsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.safehome-gre.com/")]
    public partial class GetSensorEventsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SafeHome.SafeHomeAPIServices.SensorEvent[] GetSensorEventsResult;
        
        public GetSensorEventsResponseBody() {
        }
        
        public GetSensorEventsResponseBody(SafeHome.SafeHomeAPIServices.SensorEvent[] GetSensorEventsResult) {
            this.GetSensorEventsResult = GetSensorEventsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeactivateSystemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeactivateSystem", Namespace="http://www.safehome-gre.com/", Order=0)]
        public SafeHome.SafeHomeAPIServices.DeactivateSystemRequestBody Body;
        
        public DeactivateSystemRequest() {
        }
        
        public DeactivateSystemRequest(SafeHome.SafeHomeAPIServices.DeactivateSystemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.safehome-gre.com/")]
    public partial class DeactivateSystemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int customerID;
        
        public DeactivateSystemRequestBody() {
        }
        
        public DeactivateSystemRequestBody(int customerID) {
            this.customerID = customerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeactivateSystemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeactivateSystemResponse", Namespace="http://www.safehome-gre.com/", Order=0)]
        public SafeHome.SafeHomeAPIServices.DeactivateSystemResponseBody Body;
        
        public DeactivateSystemResponse() {
        }
        
        public DeactivateSystemResponse(SafeHome.SafeHomeAPIServices.DeactivateSystemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.safehome-gre.com/")]
    public partial class DeactivateSystemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeactivateSystemResult;
        
        public DeactivateSystemResponseBody() {
        }
        
        public DeactivateSystemResponseBody(string DeactivateSystemResult) {
            this.DeactivateSystemResult = DeactivateSystemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivateSystemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivateSystem", Namespace="http://www.safehome-gre.com/", Order=0)]
        public SafeHome.SafeHomeAPIServices.ActivateSystemRequestBody Body;
        
        public ActivateSystemRequest() {
        }
        
        public ActivateSystemRequest(SafeHome.SafeHomeAPIServices.ActivateSystemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.safehome-gre.com/")]
    public partial class ActivateSystemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int customerID;
        
        public ActivateSystemRequestBody() {
        }
        
        public ActivateSystemRequestBody(int customerID) {
            this.customerID = customerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivateSystemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivateSystemResponse", Namespace="http://www.safehome-gre.com/", Order=0)]
        public SafeHome.SafeHomeAPIServices.ActivateSystemResponseBody Body;
        
        public ActivateSystemResponse() {
        }
        
        public ActivateSystemResponse(SafeHome.SafeHomeAPIServices.ActivateSystemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.safehome-gre.com/")]
    public partial class ActivateSystemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ActivateSystemResult;
        
        public ActivateSystemResponseBody() {
        }
        
        public ActivateSystemResponseBody(string ActivateSystemResult) {
            this.ActivateSystemResult = ActivateSystemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RestartSystemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RestartSystem", Namespace="http://www.safehome-gre.com/", Order=0)]
        public SafeHome.SafeHomeAPIServices.RestartSystemRequestBody Body;
        
        public RestartSystemRequest() {
        }
        
        public RestartSystemRequest(SafeHome.SafeHomeAPIServices.RestartSystemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.safehome-gre.com/")]
    public partial class RestartSystemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int customerID;
        
        public RestartSystemRequestBody() {
        }
        
        public RestartSystemRequestBody(int customerID) {
            this.customerID = customerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RestartSystemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RestartSystemResponse", Namespace="http://www.safehome-gre.com/", Order=0)]
        public SafeHome.SafeHomeAPIServices.RestartSystemResponseBody Body;
        
        public RestartSystemResponse() {
        }
        
        public RestartSystemResponse(SafeHome.SafeHomeAPIServices.RestartSystemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.safehome-gre.com/")]
    public partial class RestartSystemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RestartSystemResult;
        
        public RestartSystemResponseBody() {
        }
        
        public RestartSystemResponseBody(string RestartSystemResult) {
            this.RestartSystemResult = RestartSystemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitReadingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitReading", Namespace="http://www.safehome-gre.com/", Order=0)]
        public SafeHome.SafeHomeAPIServices.SubmitReadingRequestBody Body;
        
        public SubmitReadingRequest() {
        }
        
        public SubmitReadingRequest(SafeHome.SafeHomeAPIServices.SubmitReadingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.safehome-gre.com/")]
    public partial class SubmitReadingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int customerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int sensorID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string detail;
        
        public SubmitReadingRequestBody() {
        }
        
        public SubmitReadingRequestBody(int customerID, int sensorID, string detail) {
            this.customerID = customerID;
            this.sensorID = sensorID;
            this.detail = detail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitReadingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitReadingResponse", Namespace="http://www.safehome-gre.com/", Order=0)]
        public SafeHome.SafeHomeAPIServices.SubmitReadingResponseBody Body;
        
        public SubmitReadingResponse() {
        }
        
        public SubmitReadingResponse(SafeHome.SafeHomeAPIServices.SubmitReadingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.safehome-gre.com/")]
    public partial class SubmitReadingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubmitReadingResult;
        
        public SubmitReadingResponseBody() {
        }
        
        public SubmitReadingResponseBody(string SubmitReadingResult) {
            this.SubmitReadingResult = SubmitReadingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SafeHomeAPISoapChannel : SafeHome.SafeHomeAPIServices.SafeHomeAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SafeHomeAPISoapClient : System.ServiceModel.ClientBase<SafeHome.SafeHomeAPIServices.SafeHomeAPISoap>, SafeHome.SafeHomeAPIServices.SafeHomeAPISoap {
        
        public SafeHomeAPISoapClient() {
        }
        
        public SafeHomeAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SafeHomeAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SafeHomeAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SafeHomeAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafeHome.SafeHomeAPIServices.GetSystemStateResponse SafeHome.SafeHomeAPIServices.SafeHomeAPISoap.GetSystemState(SafeHome.SafeHomeAPIServices.GetSystemStateRequest request) {
            return base.Channel.GetSystemState(request);
        }
        
        public string GetSystemState(int customerID) {
            SafeHome.SafeHomeAPIServices.GetSystemStateRequest inValue = new SafeHome.SafeHomeAPIServices.GetSystemStateRequest();
            inValue.Body = new SafeHome.SafeHomeAPIServices.GetSystemStateRequestBody();
            inValue.Body.customerID = customerID;
            SafeHome.SafeHomeAPIServices.GetSystemStateResponse retVal = ((SafeHome.SafeHomeAPIServices.SafeHomeAPISoap)(this)).GetSystemState(inValue);
            return retVal.Body.GetSystemStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafeHome.SafeHomeAPIServices.GetSystemStateResponse> SafeHome.SafeHomeAPIServices.SafeHomeAPISoap.GetSystemStateAsync(SafeHome.SafeHomeAPIServices.GetSystemStateRequest request) {
            return base.Channel.GetSystemStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafeHome.SafeHomeAPIServices.GetSystemStateResponse> GetSystemStateAsync(int customerID) {
            SafeHome.SafeHomeAPIServices.GetSystemStateRequest inValue = new SafeHome.SafeHomeAPIServices.GetSystemStateRequest();
            inValue.Body = new SafeHome.SafeHomeAPIServices.GetSystemStateRequestBody();
            inValue.Body.customerID = customerID;
            return ((SafeHome.SafeHomeAPIServices.SafeHomeAPISoap)(this)).GetSystemStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafeHome.SafeHomeAPIServices.GetSensorEventsResponse SafeHome.SafeHomeAPIServices.SafeHomeAPISoap.GetSensorEvents(SafeHome.SafeHomeAPIServices.GetSensorEventsRequest request) {
            return base.Channel.GetSensorEvents(request);
        }
        
        public SafeHome.SafeHomeAPIServices.SensorEvent[] GetSensorEvents(int customerID) {
            SafeHome.SafeHomeAPIServices.GetSensorEventsRequest inValue = new SafeHome.SafeHomeAPIServices.GetSensorEventsRequest();
            inValue.Body = new SafeHome.SafeHomeAPIServices.GetSensorEventsRequestBody();
            inValue.Body.customerID = customerID;
            SafeHome.SafeHomeAPIServices.GetSensorEventsResponse retVal = ((SafeHome.SafeHomeAPIServices.SafeHomeAPISoap)(this)).GetSensorEvents(inValue);
            return retVal.Body.GetSensorEventsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafeHome.SafeHomeAPIServices.GetSensorEventsResponse> SafeHome.SafeHomeAPIServices.SafeHomeAPISoap.GetSensorEventsAsync(SafeHome.SafeHomeAPIServices.GetSensorEventsRequest request) {
            return base.Channel.GetSensorEventsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafeHome.SafeHomeAPIServices.GetSensorEventsResponse> GetSensorEventsAsync(int customerID) {
            SafeHome.SafeHomeAPIServices.GetSensorEventsRequest inValue = new SafeHome.SafeHomeAPIServices.GetSensorEventsRequest();
            inValue.Body = new SafeHome.SafeHomeAPIServices.GetSensorEventsRequestBody();
            inValue.Body.customerID = customerID;
            return ((SafeHome.SafeHomeAPIServices.SafeHomeAPISoap)(this)).GetSensorEventsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafeHome.SafeHomeAPIServices.DeactivateSystemResponse SafeHome.SafeHomeAPIServices.SafeHomeAPISoap.DeactivateSystem(SafeHome.SafeHomeAPIServices.DeactivateSystemRequest request) {
            return base.Channel.DeactivateSystem(request);
        }
        
        public string DeactivateSystem(int customerID) {
            SafeHome.SafeHomeAPIServices.DeactivateSystemRequest inValue = new SafeHome.SafeHomeAPIServices.DeactivateSystemRequest();
            inValue.Body = new SafeHome.SafeHomeAPIServices.DeactivateSystemRequestBody();
            inValue.Body.customerID = customerID;
            SafeHome.SafeHomeAPIServices.DeactivateSystemResponse retVal = ((SafeHome.SafeHomeAPIServices.SafeHomeAPISoap)(this)).DeactivateSystem(inValue);
            return retVal.Body.DeactivateSystemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafeHome.SafeHomeAPIServices.DeactivateSystemResponse> SafeHome.SafeHomeAPIServices.SafeHomeAPISoap.DeactivateSystemAsync(SafeHome.SafeHomeAPIServices.DeactivateSystemRequest request) {
            return base.Channel.DeactivateSystemAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafeHome.SafeHomeAPIServices.DeactivateSystemResponse> DeactivateSystemAsync(int customerID) {
            SafeHome.SafeHomeAPIServices.DeactivateSystemRequest inValue = new SafeHome.SafeHomeAPIServices.DeactivateSystemRequest();
            inValue.Body = new SafeHome.SafeHomeAPIServices.DeactivateSystemRequestBody();
            inValue.Body.customerID = customerID;
            return ((SafeHome.SafeHomeAPIServices.SafeHomeAPISoap)(this)).DeactivateSystemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafeHome.SafeHomeAPIServices.ActivateSystemResponse SafeHome.SafeHomeAPIServices.SafeHomeAPISoap.ActivateSystem(SafeHome.SafeHomeAPIServices.ActivateSystemRequest request) {
            return base.Channel.ActivateSystem(request);
        }
        
        public string ActivateSystem(int customerID) {
            SafeHome.SafeHomeAPIServices.ActivateSystemRequest inValue = new SafeHome.SafeHomeAPIServices.ActivateSystemRequest();
            inValue.Body = new SafeHome.SafeHomeAPIServices.ActivateSystemRequestBody();
            inValue.Body.customerID = customerID;
            SafeHome.SafeHomeAPIServices.ActivateSystemResponse retVal = ((SafeHome.SafeHomeAPIServices.SafeHomeAPISoap)(this)).ActivateSystem(inValue);
            return retVal.Body.ActivateSystemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafeHome.SafeHomeAPIServices.ActivateSystemResponse> SafeHome.SafeHomeAPIServices.SafeHomeAPISoap.ActivateSystemAsync(SafeHome.SafeHomeAPIServices.ActivateSystemRequest request) {
            return base.Channel.ActivateSystemAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafeHome.SafeHomeAPIServices.ActivateSystemResponse> ActivateSystemAsync(int customerID) {
            SafeHome.SafeHomeAPIServices.ActivateSystemRequest inValue = new SafeHome.SafeHomeAPIServices.ActivateSystemRequest();
            inValue.Body = new SafeHome.SafeHomeAPIServices.ActivateSystemRequestBody();
            inValue.Body.customerID = customerID;
            return ((SafeHome.SafeHomeAPIServices.SafeHomeAPISoap)(this)).ActivateSystemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafeHome.SafeHomeAPIServices.RestartSystemResponse SafeHome.SafeHomeAPIServices.SafeHomeAPISoap.RestartSystem(SafeHome.SafeHomeAPIServices.RestartSystemRequest request) {
            return base.Channel.RestartSystem(request);
        }
        
        public string RestartSystem(int customerID) {
            SafeHome.SafeHomeAPIServices.RestartSystemRequest inValue = new SafeHome.SafeHomeAPIServices.RestartSystemRequest();
            inValue.Body = new SafeHome.SafeHomeAPIServices.RestartSystemRequestBody();
            inValue.Body.customerID = customerID;
            SafeHome.SafeHomeAPIServices.RestartSystemResponse retVal = ((SafeHome.SafeHomeAPIServices.SafeHomeAPISoap)(this)).RestartSystem(inValue);
            return retVal.Body.RestartSystemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafeHome.SafeHomeAPIServices.RestartSystemResponse> SafeHome.SafeHomeAPIServices.SafeHomeAPISoap.RestartSystemAsync(SafeHome.SafeHomeAPIServices.RestartSystemRequest request) {
            return base.Channel.RestartSystemAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafeHome.SafeHomeAPIServices.RestartSystemResponse> RestartSystemAsync(int customerID) {
            SafeHome.SafeHomeAPIServices.RestartSystemRequest inValue = new SafeHome.SafeHomeAPIServices.RestartSystemRequest();
            inValue.Body = new SafeHome.SafeHomeAPIServices.RestartSystemRequestBody();
            inValue.Body.customerID = customerID;
            return ((SafeHome.SafeHomeAPIServices.SafeHomeAPISoap)(this)).RestartSystemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafeHome.SafeHomeAPIServices.SubmitReadingResponse SafeHome.SafeHomeAPIServices.SafeHomeAPISoap.SubmitReading(SafeHome.SafeHomeAPIServices.SubmitReadingRequest request) {
            return base.Channel.SubmitReading(request);
        }
        
        public string SubmitReading(int customerID, int sensorID, string detail) {
            SafeHome.SafeHomeAPIServices.SubmitReadingRequest inValue = new SafeHome.SafeHomeAPIServices.SubmitReadingRequest();
            inValue.Body = new SafeHome.SafeHomeAPIServices.SubmitReadingRequestBody();
            inValue.Body.customerID = customerID;
            inValue.Body.sensorID = sensorID;
            inValue.Body.detail = detail;
            SafeHome.SafeHomeAPIServices.SubmitReadingResponse retVal = ((SafeHome.SafeHomeAPIServices.SafeHomeAPISoap)(this)).SubmitReading(inValue);
            return retVal.Body.SubmitReadingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafeHome.SafeHomeAPIServices.SubmitReadingResponse> SafeHome.SafeHomeAPIServices.SafeHomeAPISoap.SubmitReadingAsync(SafeHome.SafeHomeAPIServices.SubmitReadingRequest request) {
            return base.Channel.SubmitReadingAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafeHome.SafeHomeAPIServices.SubmitReadingResponse> SubmitReadingAsync(int customerID, int sensorID, string detail) {
            SafeHome.SafeHomeAPIServices.SubmitReadingRequest inValue = new SafeHome.SafeHomeAPIServices.SubmitReadingRequest();
            inValue.Body = new SafeHome.SafeHomeAPIServices.SubmitReadingRequestBody();
            inValue.Body.customerID = customerID;
            inValue.Body.sensorID = sensorID;
            inValue.Body.detail = detail;
            return ((SafeHome.SafeHomeAPIServices.SafeHomeAPISoap)(this)).SubmitReadingAsync(inValue);
        }
    }
}
