CREATE TABLE PDC_Customer (
  CustomerID Int IDENTITY (1,1) NOT NULL PRIMARY KEY,
  Username Varchar(255) NOT NULL,
  Password Varchar(255) NOT NULL
);

CREATE TABLE PDC_Floor(
FloorID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
FloorNum INT NOT NULL,
NoOfRooms INT NOT NULL,
CustomerID INT FOREIGN KEY REFERENCES PDC_Customer(CustomerID) ON DELETE CASCADE
);

CREATE TABLE PDC_Room (
  RoomID Int NOT NULL IDENTITY (1,1) PRIMARY KEY,
  RoomName Varchar(255) NOT NULL,
  CustomerID Int NOT NULL FOREIGN KEY REFERENCES PDC_Customer(CustomerID) ON DELETE CASCADE,
  FloorID Int NOT NULL FOREIGN KEY REFERENCES PDC_Floor(FloorID),
  RoomIDNorth Int FOREIGN KEY REFERENCES PDC_Room(RoomID),
  DoorNorth BIT DEFAULT 0,
  RoomIDEast Int FOREIGN KEY REFERENCES PDC_Room(RoomID),
  DoorEast BIT DEFAULT 0,
  RoomIDSouth Int FOREIGN KEY REFERENCES PDC_Room(RoomID),
  DoorSouth BIT DEFAULT 0,
  RoomIDWest Int FOREIGN KEY REFERENCES PDC_Room(RoomID),
  DoorWest BIT DEFAULT 0
);

CREATE TABLE PDC_SensorType (
  SensorTypeID Int NOT NULL IDENTITY (1,1) PRIMARY KEY,
  SensorName Varchar(255) NOT NULL
);

CREATE TABLE PDC_Sensor (
  SensorID Int NOT NULL IDENTITY (1,1) PRIMARY KEY,
  SensorTypeID Int NOT NULL FOREIGN KEY REFERENCES PDC_SensorType(SensorTypeID) ON DELETE CASCADE,
  RoomID Int NOT NULL FOREIGN KEY REFERENCES PDC_Room(RoomID) ON DELETE CASCADE
);

CREATE TABLE PDC_SensorEvent (
  EventID INT NOT NULL IDENTITY(1,1)PRIMARY KEY,
  SensorID INT NOT NULL FOREIGN KEY REFERENCES PDC_Sensor(SensorID) ON DELETE CASCADE,
  EventTime DATETIME NOT NULL DEFAULT GETDATE(),
  Detail VARCHAR(255)
);