CREATE TABLE PDC_SensorEvent (
EventID INT NOT NULL IDENTITY(1,1)PRIMARY KEY,
SensorID INT NOT NULL FOREIGN KEY REFERENCES PDC_Sensor(SensorID),
EventTime DATETIME NOT NULL DEFAULT GETDATE(),
Detail VARCHAR(255)
);